apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: k1-eks
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta2
    kind: AWSManagedControlPlane
    name: k1-eks-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
    kind: AWSManagedCluster
    name: k1-eks
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedCluster
metadata:
  name: k1-eks
  namespace: default
spec: {}
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta2
kind: AWSManagedControlPlane
metadata:
  name: k1-eks-control-plane
  namespace: default
spec:
  region: eu-central-1
  sshKeyName: jchlapinski
  version: v1.27.2
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachinePool
metadata:
  name: k1-eks-pool-0
  namespace: default
spec:
  clusterName: k1-eks
  replicas: 4
  template:
    spec:
      bootstrap:
        dataSecretName: ""
      clusterName: k1-eks
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
        kind: AWSManagedMachinePool
        name: k1-eks-pool-0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta2
kind: AWSManagedMachinePool
metadata:
  name: k1-eks-pool-0
  namespace: default
spec: {}
