apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k1-eks
spec:
  destination:
    name: ''
    namespace: 'default'
    server: 'https://kubernetes.default.svc'
  source:
    path: 'k1-eks'
    repoURL: 'https://github.com/jchlapinski/k8sexp.git'
    targetRevision: HEAD
    #helm:
     # valueFiles:
       # - values-c1.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
